CREATE TABLE livro (
  ISBN int(11) NOT NULL ,
  titulo varchar(30) NOT NULL 
);

ALTER TABLE livro ADD CONSTRAINT LC PRIMARY KEY (ISBN);

ALTER TABLE livro ADD CONSTRAINT  FOREIGN KEY () REFERENCES Autor ();
ALTER TABLE livro ADD CONSTRAINT  FOREIGN KEY () REFERENCES Biblioteca ();
